cmake_minimum_required(VERSION 4.0.0)
set(CMAKE_EXPERIMENTAL_CXX_IMPORT_STD "451f2fe2-a8a2-47c3-bc32-94786d8fc91b")
set(CMAKE_CXX_MODULE_STD ON)
set(CMAKE_CXX_STANDARD 23)
project(kaart4)
add_library(ADCCard)
target_sources(ADCCard PUBLIC FILE_SET CXX_MODULES FILES ADCCard.cppm)
target_sources(ADCCard PUBLIC ADCCard.cpp)
add_library(AD178)
target_sources(AD178 PUBLIC FILE_SET CXX_MODULES FILES AD178.cppm)
target_sources(AD178 PUBLIC AD178.cpp)
target_link_libraries(AD178 ADCCard)
add_library(NI323)
target_sources(NI323 PUBLIC FILE_SET CXX_MODULES FILES NI323.cppm)
target_sources(NI323 PUBLIC NI323.cpp)
target_link_libraries(NI323 ADCCard)
add_library(BB647)
target_sources(BB647 PUBLIC FILE_SET CXX_MODULES FILES BB647.cppm)
target_sources(BB647 PUBLIC BB647.cpp)
target_link_libraries(BB647 ADCCard)
add_library(do_measurement)
target_sources(do_measurement PUBLIC FILE_SET CXX_MODULES FILES do_measurement.cppm)
target_sources(do_measurement PUBLIC do_measurement.cpp)
target_link_libraries(do_measurement ADCCard)
add_executable(kaart4 kaart4.cpp)
set(CMAKE_CPP_FLAGS "${CMAKE_CPP_FLAGS} -std=c++23 -Wall -Wextra -Wpedantic -g3 -O0")
target_link_libraries(kaart4 AD178 NI323 BB647 ADCCard do_measurement)
